"""The Perseus analysis-output adapter (`ARCHITECTURE.md` §3, ADR-0017, `ONTOLOGY.md` §5.4).

First of the two adapter classes and deliberately the smaller one. ADR-0017 puts the platform
*downstream* of the tools a researcher already uses, and the collaborating group's tool is Perseus;
`ARCHITECTURE.md` §3 describes what it emits as *"a flat file of proteins, differences and
significance values, with no localisation or razor-pick complexity."* That sentence is the whole
design of this module: the grain is **protein**, so a row becomes a `ProteinObservation` anchored on
a `Protein`, and there is no `ModificationSite`, no `ProteinSequence`, no sequence version to
resolve and therefore no network call in the ingestion path.

**`parameters_observed = false` is not a flag, it is the reason this class of adapter exists**
(I19, §5.4). When the platform computes a result it knows the test, the thresholds and the filtered
rows because it performed them. A Perseus table states none of them — it is a matrix of numbers with
column headings. So the parameters arrive **declared** by the caller, in `DeclaredAnalysis`, and the
adapter refuses without them rather than inventing a default that would then be indistinguishable
from something observed. Everything this module writes carries `parameters_observed = false`, and
under §5.4 that propagates to every `DifferentialResult` generated by the analysis.

Three details that produce numbers rather than errors when got wrong, so each is handled explicitly:

1. **`-Log` p-values.** Perseus writes `-Log Student's T-test p-value <suffix>` by default. Read as
   a p-value, `4.51` says "not remotely significant" where `3.09e-05` is meant. Both spellings are
   recognised and the `-Log` form is converted; a file carrying both is an error rather than a
   preference, because the two disagreeing would mean the file is not what it claims.
2. **CRLF.** The PXD018299 deposit is CRLF throughout (`ARCHITECTURE.md` §3) and a Windows Perseus
   export will be too. Splitting on `\\n` by hand leaves `\\r` on the last field of every row, so a
   lookup on the last column silently returns nothing. `splitlines()` handles both; nothing here
   splits on a literal newline.
3. **Protein groups.** A row naming `P19525;O43593` measured the *group*, and 72-77% of real rows
   do (`ROADMAP.md` § Protein-group ambiguity). This adapter refused every one of them until
   ADR-0022, because `ProteinObservation` was keyed on a single `Protein` anchor and choosing which
   is the razor pick I14 forbids. Since ADR-0022 the group **is** the identity: `candidate_proteins`
   is identifying and `RESOLVES_TO_PROTEIN` is `MANY_MANY`, so the observation names every member
   and asserts a pick among none of them.

   The set read is **`Protein IDs`, not `Majority protein IDs`**, where both are present. §6.3:
   *"MaxQuant's `Leading proteins` and `Protein` columns are its own razor-rule inference, not
   ground truth"* — and `Majority protein IDs` is that inference, being the subset carrying at
   least half the peptides. An observation records what was observed, so it takes the wider column.
   The two differ on 52-72% of rows, so this is not a formality.

I13 holds: `search_engine`, `acquisition_mode` and the rest are recorded on the `Dataset`, never
branched on. The `-Log` detection above is a branch on *file content*, which is what an adapter is
for, not a branch on recorded pipeline metadata.
"""

from __future__ import annotations

from collections.abc import Callable, Mapping
from dataclasses import dataclass, field
from pathlib import Path

from bzk.adapters.base import Edge, Node, ParsedObservations, SampleMapping, sample_nodes
from bzk.ontology import invariants, schema
from bzk.ontology.invariants import NODE_TYPE_KEY
from bzk.ontology.keys import evidence_id, protein_key
from bzk.provenance.raw_store import content_hash
from bzk.resolve.nodes import ResolvedProteins

#: `perseus.py` resolves nothing (ADR-0017: no network in the parse path), so every protein it
#: names is one the resolver never saw. An empty `ResolvedProteins` is exactly that statement, and
#: routing through it keeps one home for what an unresolved protein carries.
_UNRESOLVED = ResolvedProteins(nodes=[], edges=[], protein_id={})

#: Perseus writes annotation rows between the header and the data, each prefixed `#!{...}`.
#: Only the prefix is relied on. The rows' internal layout is not parsed — the adapter needs named
#: columns, not column types, and depending on a format detail it does not need would be inventing
#: precision it cannot check against a real export.
ANNOTATION_PREFIX = "#!{"

#: Perseus' conventional two-sample-test column names, per contrast suffix.
DIFFERENCE = "Student's T-test Difference {suffix}"
Q_VALUE = "Student's T-test q-value {suffix}"
P_VALUE = "Student's T-test p-value {suffix}"
MINUS_LOG_P = "-Log Student's T-test p-value {suffix}"

#: Where the observed accession set lives, **widest first**. `Protein IDs` before
#: `Majority protein IDs` deliberately: the majority subset is MaxQuant's own inference (§6.3), and
#: an observation records what was observed. `Protein` last — it is a single razor pick, usable only
#: when nothing better is in the file.
PROTEIN_COLUMNS = ("Protein IDs", "Majority protein IDs", "Proteins", "Protein")
PEPTIDE_COUNT_COLUMNS = ("Peptides", "Razor + unique peptides")


class PerseusError(ValueError):
    """A Perseus table cannot be ingested. Never downgraded to a warning (`CLAUDE.md`)."""


@dataclass(frozen=True)
class DeclaredContrast:
    """One contrast the caller states, tying a Perseus column suffix to its two arms.

    Perseus builds the suffix from its own group names, which are not the platform's condition
    labels, so the mapping is declared. `numerator` and `denominator` are identifying on `Contrast`
    (§3); the suffix is not — it never reaches the graph and exists only to find the columns.
    """

    column_suffix: str
    numerator: str
    denominator: str


@dataclass(frozen=True)
class DeclaredAnalysis:
    """The parameters of a run the platform did not witness — §5.4's *stated*, not *observed*.

    Every field here would be discovered by the platform if it had performed the analysis, and is
    unavailable from the output file. Declaring them is what `parameters_observed = false` means;
    guessing them would make a reported parameter indistinguishable from an observed one, which is
    the promotion I19 exists to refuse.
    """

    quantity: str
    filters_applied: list[str]
    test: str
    fdr_method: str
    external_version: str
    parameters_json: str | None = None
    #: Perseus imputes by default, and I15 requires an `Analysis` producing results to declare an
    #: `Imputation` — including `method='none'` where nothing was imputed. The default is `none`
    #: because that is the only claim an undeclared file supports; a downshifted-normal run must
    #: state its seed or I15 rejects it, which is the invariant working rather than obstructing.
    imputation: dict[str, object] = field(default_factory=lambda: {"method": "none"})


class PerseusAdapter:
    """`ObservationAdapter` for a Perseus result table (`ARCHITECTURE.md` §3)."""

    name = "perseus"

    def __init__(self, declared: DeclaredAnalysis, contrasts: list[DeclaredContrast]) -> None:
        if declared.quantity not in schema.QUANTITY_VALUES:
            raise PerseusError(
                f"declared quantity {declared.quantity!r} is not in the closed enum "
                f"{sorted(schema.QUANTITY_VALUES)} (ONTOLOGY.md §5, I16). It is identifying on "
                "Analysis (§3), so a misspelling forks an id rather than failing."
            )
        if not contrasts:
            raise PerseusError("at least one contrast must be declared; the file does not name one")
        self.declared = declared
        self.contrasts = list(contrasts)

    # ── sniff ───────────────────────────────────────────────────────────────────────────────────

    def sniff(self, path: Path) -> bool:
        """True for a tab-separated file carrying at least one Perseus annotation row.

        Content, not name (`ARCHITECTURE.md` §3): the MaxQuant site table this group also produces
        is `.txt` and tab-separated too, so a suffix distinguishes nothing.
        """
        try:
            lines = path.read_text(encoding="utf-8", errors="strict").splitlines()
        except (OSError, UnicodeDecodeError):
            return False
        if not lines or "\t" not in lines[0]:
            return False
        return any(line.startswith(ANNOTATION_PREFIX) for line in lines[1:])

    # ── parse ───────────────────────────────────────────────────────────────────────────────────

    def parse(self, path: Path, mapping: SampleMapping) -> ParsedObservations:
        """One Perseus table into a self-contained change-set (ADR-0019)."""
        if not mapping.samples:
            raise PerseusError(
                "the SampleMapping carries no samples, so nothing links these results to a curation "
                "activity; every result would be permanently `unprovenanced` (I5, ONTOLOGY.md §5.3)"
            )
        if not self.sniff(path):
            raise PerseusError(
                f"{path} does not look like a Perseus matrix — no {ANNOTATION_PREFIX!r} annotation "
                "row after the header. Refused rather than half-read."
            )

        raw = path.read_bytes()
        header, rows = self._read(raw, path)
        columns = {name: i for i, name in enumerate(header)}
        protein_column = self._one_of(columns, PROTEIN_COLUMNS, "protein accession")
        peptide_column = next((c for c in PEPTIDE_COUNT_COLUMNS if c in columns), None)
        readers = [self._contrast_reader(columns, c) for c in self.contrasts]

        nodes: list[Node] = sample_nodes(mapping)
        edges: list[Edge] = []

        dataset = {
            "label": path.name,
            "content_hash": content_hash(raw),
            "source": "local",
        }
        dataset_id = evidence_id("Dataset", dataset)
        nodes.append(self._node("Dataset", dataset_id, dataset))
        for sample in mapping.samples:
            edges.append({"type": "PRODUCED", "from": sample["id"], "to": dataset_id})

        analysis = {
            "kind": "external",
            "external_tool": self.name,
            "external_version": self.declared.external_version,
            # I19. The one field that decides whether these numbers may ever be read as though the
            # platform produced them.
            "parameters_observed": False,
            "quantity": self.declared.quantity,
            "filters_applied": sorted(self.declared.filters_applied),
            "test": self.declared.test,
            "fdr_method": self.declared.fdr_method,
            "parameters_json": self.declared.parameters_json,
            # Determined by `kind`: `basis` and `confidence` are curation's fields (§3, §5.3).
            "basis": None,
            "confidence": None,
            # Determined by `quantity`: a protein-grain quantity has no residues to localise (§6.4).
            "localization_threshold": None,
        }
        imputation = dict(self.declared.imputation)
        analysis_id = evidence_id(
            "Analysis", analysis, {"Dataset": dataset_id}, {"Imputation": [imputation]}
        )
        nodes.append(self._node("Analysis", analysis_id, analysis))
        edges.append({"type": "USED", "from": analysis_id, "to": dataset_id})

        imputation_id = evidence_id("Imputation", imputation, {"Analysis": analysis_id})
        nodes.append(self._node("Imputation", imputation_id, imputation))
        edges.append({"type": "IMPUTATION_FOR", "from": imputation_id, "to": analysis_id})

        contrast_ids = {}
        for declared in self.contrasts:
            props = {"numerator": declared.numerator, "denominator": declared.denominator}
            contrast_id = evidence_id("Contrast", props)
            contrast_ids[declared.column_suffix] = contrast_id
            nodes.append(self._node("Contrast", contrast_id, props))

        for line_no, row in rows:
            accessions = self._accessions(row[protein_column], line_no)
            protein_ids = [protein_key(a) for a in accessions]
            # `perseus.py` resolves nothing — ADR-0017 keeps the network out of the parse path — so
            # every one of its proteins is `gene_absence = 'unresolved'`, and the one place that
            # rule lives is `ResolvedProteins.candidate_nodes` (`bzk/resolve/nodes.py`). Called
            # against an empty resolution rather than reimplemented, so the two adapters cannot
            # drift on what an unresolved protein carries.
            nodes.extend(_UNRESOLVED.candidate_nodes(accessions))

            # `candidate_proteins` is identifying and `keys.canonical_value` sorts `STRING[]` before
            # hashing, so the file's ordering — which is MaxQuant's ranking, an inference — cannot
            # fork an id (I7).
            observation: dict[str, object] = {"candidate_proteins": protein_ids}
            if peptide_column is not None and row[columns[peptide_column]].strip():
                observation["n_peptides"] = int(row[columns[peptide_column]])
            observation_id = evidence_id("ProteinObservation", observation, {"Dataset": dataset_id})
            nodes.append(self._node("ProteinObservation", observation_id, observation))
            edges.append({"type": "REPORTS_PROTEIN", "from": dataset_id, "to": observation_id})
            for protein_id in protein_ids:
                edges.append(
                    {"type": "RESOLVES_TO_PROTEIN", "from": observation_id, "to": protein_id}
                )

            for declared, reader in zip(self.contrasts, readers, strict=True):
                result = reader(row)
                # I4: protein-grain results are the uncorrected kind by construction — there is no
                # matched proteome above a protein to correct it against, so `adjustment_method`
                # stays null (§3 classifies that absence as determined by `protein_adjusted`).
                result["protein_adjusted"] = "not_applied"
                result["adjustment_method"] = None
                contrast_id = contrast_ids[declared.column_suffix]
                result_id = evidence_id(
                    "DifferentialResult",
                    result,
                    {
                        "Analysis": analysis_id,
                        "ProteinObservation": observation_id,
                        "Contrast": contrast_id,
                    },
                )
                nodes.append(self._node("DifferentialResult", result_id, result))
                edges.append({"type": "WAS_GENERATED_BY", "from": result_id, "to": analysis_id})
                edges.append(
                    {"type": "RESULT_FOR_PROTEIN", "from": result_id, "to": observation_id}
                )
                edges.append({"type": "RESULT_IN_CONTRAST", "from": result_id, "to": contrast_id})

        nodes = self._deduplicate(nodes)
        # Held to the same contract as the curation loader's output: a batch that cannot pass
        # validation never leaves this module half-written.
        invariants.validate(nodes, edges)
        return ParsedObservations(nodes=nodes, edges=edges)

    # ── internals ───────────────────────────────────────────────────────────────────────────────

    def _read(self, raw: bytes, path: Path) -> tuple[list[str], list[tuple[int, list[str]]]]:
        """Header and data rows, annotation rows dropped.

        Bytes in, decoded here, split with `splitlines()` — see the module docstring on CRLF. The
        caller passes the bytes it hashed, so the `Dataset` digest and the parsed content are the
        same read of the same file.
        """
        lines = raw.decode("utf-8").splitlines()
        header = lines[0].split("\t")
        rows = []
        for line_no, line in enumerate(lines[1:], start=2):
            if not line.strip() or line.startswith(ANNOTATION_PREFIX):
                continue
            fields = line.split("\t")
            if len(fields) < len(header):
                fields += [""] * (len(header) - len(fields))  # Perseus omits trailing empties
            rows.append((line_no, fields))
        if not rows:
            raise PerseusError(f"{path} has a header and annotation rows but no data")
        return header, rows

    @staticmethod
    def _one_of(columns: dict[str, int], candidates: tuple[str, ...], what: str) -> int:
        for name in candidates:
            if name in columns:
                return columns[name]
        raise PerseusError(
            f"no {what} column: expected one of {list(candidates)}, found {sorted(columns)}"
        )

    def _contrast_reader(
        self, columns: dict[str, int], declared: DeclaredContrast
    ) -> Callable[[list[str]], dict[str, object]]:
        """Bind the three result columns for one contrast, or say which is missing.

        Resolved once per parse rather than per row: a missing column is a property of the file, and
        discovering it on row 4,000 would already have emitted 3,999 wrong nodes.
        """
        suffix = declared.column_suffix
        difference = DIFFERENCE.format(suffix=suffix)
        q_value = Q_VALUE.format(suffix=suffix)
        plain_p = P_VALUE.format(suffix=suffix)
        minus_log_p = MINUS_LOG_P.format(suffix=suffix)

        missing = [c for c in (difference, q_value) if c not in columns]
        if plain_p not in columns and minus_log_p not in columns:
            missing.append(f"{plain_p!r} or {minus_log_p!r}")
        if missing:
            raise PerseusError(
                f"declared contrast {suffix!r} has no columns in this file — missing {missing}. "
                "Refused rather than emitting nothing, which would read as a null result."
            )
        if plain_p in columns and minus_log_p in columns:
            raise PerseusError(
                f"contrast {suffix!r} carries both {plain_p!r} and {minus_log_p!r}; the file is not "
                "what it claims and picking one would be a guess about which is authoritative"
            )
        negated = plain_p not in columns
        p_index = columns[minus_log_p if negated else plain_p]

        def read(row: list[str]) -> dict[str, object]:
            raw_p = float(row[p_index])
            return {
                "log2fc": float(row[columns[difference]]),
                # Perseus' default is the negated log; 4.51 here means p = 3.09e-05.
                "p_value": 10**-raw_p if negated else raw_p,
                "adj_p_value": float(row[columns[q_value]]),
            }

        return read

    @staticmethod
    def _accessions(cell: str, line_no: int) -> list[str]:
        """The observed candidate set for one row. A group of one is a group.

        No `ProteinAssignment` is emitted here. Where a file carries both columns, MaxQuant's
        narrowing to `Majority protein IDs` is an inference worth recording — but §6.3's shape is
        candidate set plus a *concluded protein* (`ASSIGNS_PROTEIN`), and a narrowing to a smaller
        *subset* is neither. Representing it needs a modelling decision ADR-0022 did not make, and
        an adapter is the wrong place to make one. Recorded in `HANDOFF.md` §8.
        """
        accessions = [a.strip() for a in cell.split(";") if a.strip()]
        if not accessions:
            raise PerseusError(
                f"line {line_no}: no protein accession. A row that names none cannot become a "
                "ProteinObservation — `candidate_proteins` is identifying (ONTOLOGY.md §3)."
            )
        return accessions

    @staticmethod
    def _node(label: str, node_id: str, props: Mapping[str, object]) -> Node:
        return {NODE_TYPE_KEY: label, "id": node_id, **props}

    @staticmethod
    def _deduplicate(nodes: list[Node]) -> list[Node]:
        """Content-derived ids converge, so one `Protein` named by two rows is one node.

        ADR-0019 rejects a duplicate id in a change-set, and I7 is what makes collapsing them safe:
        two nodes with the same id are the same node by construction, not by assumption.
        """
        seen: dict[str, Node] = {}
        for node in nodes:
            seen.setdefault(node["id"], node)
        return list(seen.values())
