"""Guards for the 12-of-14 welch_t baseline fixture (`tests/fixtures/pxd018299_welch_baseline.json`).

`HANDOFF.md` §6 records why the per-site rows are committed at all: a gene lookup that read
`Protein names` instead of `Gene names` returned "not found" fourteen times, *"which reads exactly
like a real negative result."* Three integers cannot tell "12 of 14" from "12 of 14, a different
twelve". The rows pin which twelve, at which site, on which razor pick.

Two kinds of check here, and they are not equally strong — saying so is the point of the split:

- **Offline** (always runs): the fixture against `data/curation/analysis_PXD018299_KOIFN_vs_WTIFN
  .json` and against itself. The counts are read from the curation record rather than copied into
  the fixture, so there is one home for them (`CLAUDE.md` § Single source of truth, and the pattern
  `tests/test_curation_content_hash.py` already sets for the digest).
- **Re-derivation** (skips unless the deposit is in `raw/`): `derive()` over the stored bytes. Its
  comparison against the *curation record* is a real regression check — the record was written by
  the notebook, so raw bytes and record are independent. Its comparison against the *fixture* is
  **not**: the fixture was generated by this same function. That half checks determinism and
  environment drift — a pandas or numpy upgrade silently moving the numbers — and nothing more.
  `CLAUDE.md` point 2 names the failure it would otherwise be: `test_rebuild` asserting a table
  count against its own source.

`raw/` does not survive a container (`HANDOFF.md` §3), so the re-derivation skips rather than fails
when the deposit is absent. A test that went red on every fresh session would teach sessions to
ignore it.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, cast

import pytest

from bzk.sources.pxd018299_baseline import (
    EXPECTED_TARGETS,
    SIG_ADJ_P,
    SIG_LOG2FC,
    Baseline,
    deposit_path,
    derive,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE = REPO_ROOT / "tests" / "fixtures" / "pxd018299_welch_baseline.json"
ANALYSIS_RECORD = REPO_ROOT / "data" / "curation" / "analysis_PXD018299_KOIFN_vs_WTIFN.json"

# The two targets that fall outside the thresholds (ROADMAP § Measured findings: adj p 0.24;
# log2FC +0.89). Named rather than counted: a change that "recovers" one of them must fail here
# and be explained. HANDOFF.md §5 expects `perseus_s0` to admit a different set, and that is a
# result to record, not a number to reach.
NOT_RECOVERED = ("ADAR", "PSMB9")

# Floats are compared to a tolerance and verdicts exactly. Seeded `default_rng(0)` is reproducible
# in practice, but the ziggurat stream is not part of numpy's compatibility contract; a fixture
# that goes red on a numpy patch release is a fixture sessions learn to ignore.
FLOAT_RTOL = 1e-9


def _json(path: Path) -> dict[str, Any]:
    return cast("dict[str, Any]", json.loads(path.read_text()))


def _fixture() -> dict[str, Any]:
    return _json(FIXTURE)


def _rows() -> list[dict[str, Any]]:
    return cast("list[dict[str, Any]]", _fixture()["targets"])


def _record() -> dict[str, Any]:
    return _json(ANALYSIS_RECORD)


# --------------------------------------------------------------------------------------------
# Offline: the fixture against the curation record, and against itself
# --------------------------------------------------------------------------------------------


def test_fixture_covers_exactly_the_published_targets() -> None:
    """Fourteen rows, in the notebook's order, matching the module's target list."""
    assert tuple(row["gene"] for row in _rows()) == EXPECTED_TARGETS


def test_fixture_target_count_matches_the_curation_record() -> None:
    assert len(_rows()) == _record()["n_expected_total"]


def test_fixture_recovered_count_matches_the_curation_record() -> None:
    """The 12 is read from the record, not restated in the fixture — one home for the count."""
    recovered = sum(bool(row["recovered"]) for row in _rows())
    assert recovered == _record()["n_expected_recovered"]


def test_fixture_states_no_counts_of_its_own() -> None:
    """A later edit adding `n_sites_tested` here would be the copies-diverge defect, so forbid it.

    The fixture is allowed to carry per-target `n_sites`; what it may not carry is the analysis
    counts that `data/curation/analysis_PXD018299_KOIFN_vs_WTIFN.json` owns.
    """
    owned_by_the_record = {"n_sites_tested", "n_significant_up", "n_expected_recovered",
                           "n_expected_total", "n_values_imputed", "n_values_total"}  # fmt: skip
    assert not owned_by_the_record & set(_fixture())


def test_the_two_misses_are_named() -> None:
    """ADAR and PSMB9, pinned as negatives. This is what stops the fixture being a ratchet."""
    assert tuple(row["gene"] for row in _rows() if not row["recovered"]) == NOT_RECOVERED


def test_recovered_flag_agrees_with_the_row_it_sits_on() -> None:
    """`recovered` must follow from the row's own log2fc and adj_p, or the claim has drifted.

    Catches a hand-edit that flips a verdict without touching the numbers behind it — the shape of
    edit that makes a fixture assert its own conclusion.
    """
    for row in _rows():
        if row["n_sites"] == 0:
            assert not row["recovered"]
            continue
        passes = row["adj_p"] < SIG_ADJ_P and row["log2fc"] > SIG_LOG2FC
        assert row["recovered"] == passes, row["gene"]


def test_every_target_was_detected() -> None:
    """All fourteen are present in the deposit; the two misses are threshold misses, not absences.

    The distinction matters: `n_sites = 0` would mean the gene lookup broke, which is exactly the
    silent failure `HANDOFF.md` §6 describes.
    """
    for row in _rows():
        assert row["n_sites"] > 0, row["gene"]
        assert row["protein"] and row["position"] is not None


def test_fixture_records_the_environment_it_was_generated_under() -> None:
    """The rows came out of pandas, which is a dev pin, not the platform's polars layer.

    `ROADMAP.md` § Measured findings and the fixture's own note both say reproduction under
    polars/numpy is untested. If the fixture stopped carrying that, the caveat would survive only
    in prose nobody reads next to the numbers.
    """
    generated_under = _fixture()["generated_under"]
    assert {"python", "pandas", "numpy", "scipy"} <= set(generated_under)
    assert "UNTESTED" in _fixture()["reproduction_caveat"]


# --------------------------------------------------------------------------------------------
# Re-derivation: needs the deposit in raw/
# --------------------------------------------------------------------------------------------


@pytest.fixture(scope="module")
def rederived() -> Baseline:
    try:
        path = deposit_path()
    except (FileNotFoundError, ValueError) as exc:
        pytest.skip(f"deposit not in raw/ — run `python -m bzk.sources.pride` first ({exc})")
    return derive(path)


def test_rederivation_matches_the_curation_record_counts(rederived: Baseline) -> None:
    """The one non-circular check here: raw bytes against a record the notebook wrote.

    `n_sites_tested` and `n_significant_up` were produced by `colab_reproducefigure.ipynb` cell 18
    and committed before this module existed, so agreement is evidence the transcription is
    faithful rather than evidence the code equals itself.
    """
    record = _record()
    assert rederived.n_sites_tested == record["n_sites_tested"]
    assert rederived.n_significant_up == record["n_significant_up"]
    assert rederived.n_expected_recovered == record["n_expected_recovered"]
    assert rederived.n_values_imputed == record["imputation"]["n_values_imputed"]
    assert rederived.n_values_total == record["imputation"]["n_values_total"]


def test_rederivation_reproduces_the_fixture_rows(rederived: Baseline) -> None:
    """Determinism and environment drift only — the fixture came out of this same function.

    Verdicts and identifiers exactly; floats to `FLOAT_RTOL`. A failure here means the seeded
    imputation or the test moved under a dependency upgrade, which is the reason pandas is pinned.
    """
    expected = {row["gene"]: row for row in _rows()}
    assert {row.gene for row in rederived.targets} == set(expected)
    for row in rederived.targets:
        want = expected[row.gene]
        assert row.recovered == want["recovered"], row.gene
        assert row.n_sites == want["n_sites"], row.gene
        assert row.protein == want["protein"], row.gene
        assert row.position == want["position"], row.gene
        assert row.n_candidate_proteins == want["n_candidate_proteins"], row.gene
        for field in ("loc_prob", "log2fc", "p", "adj_p"):
            assert getattr(row, field) == pytest.approx(want[field], rel=FLOAT_RTOL), (
                f"{row.gene}.{field}"
            )
